spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  datasource:
    url: "jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true"
    username: root
    password: Nasir94@
    driverClassName: "com.mysql.cj.jdbc.Driver"

accountConfigs:
  routingNo: 123456789
  baseAccountInfo: 6662233